version: '3.1'

services :
  node:
    build:
      context: .
      dockerfile: compose/Dockerfile
    restart: always
    depends_on:
      - letsencrypt

  letsencrypt:
    image: linuxserver/letsencrypt:0.36.0-ls46
    container_name: letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/config
      - ./compose/nginx-vhost:/config/nginx/site-confs/default
    environment:
      - EMAIL=tom@silkey.io
      - URL=demo.silkey.io
      - SUBDOMAINS=www
      - VALIDATION=http